"""redo the user database to be the general

Revision ID: e224f2cbfa26
Revises: 4e1cbaf68142
Create Date: 2024-07-04 17:31:13.679260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e224f2cbfa26'
down_revision: Union[str, None] = '4e1cbaf68142'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'participants', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('profiles', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('users_profile_id_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_participant_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'profile_id')
    op.drop_column('users', 'participant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('participant_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_participant_id_fkey', 'users', 'participants', ['participant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('users_profile_id_fkey', 'users', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'user_id')
    op.drop_constraint(None, 'participants', type_='foreignkey')
    op.drop_column('participants', 'user_id')
    # ### end Alembic commands ###
