"""Changed column names

Revision ID: b56ccb88bd22
Revises: 1c707ca44a76
Create Date: 2024-06-26 10:34:57.463957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b56ccb88bd22'
down_revision: Union[str, None] = '1c707ca44a76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('profiles', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('profiles', sa.Column('photo', sa.String(length=40), nullable=False))
    op.add_column('profiles', sa.Column('date_birth', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('profiles', sa.Column('sex', sa.Integer(), nullable=False))
    op.add_column('profiles', sa.Column('religion', sa.String(length=40), nullable=False))
    op.add_column('profiles', sa.Column('about', sa.String(length=1000), nullable=False))
    op.drop_column('profiles', 'Religion')
    op.drop_column('profiles', 'Photo')
    op.drop_column('profiles', 'Date_birth')
    op.drop_column('profiles', 'Sex')
    op.drop_column('profiles', 'About')
    op.drop_column('profiles', 'Name')
    op.drop_column('profiles', 'Age')
    op.add_column('users', sa.Column('profile_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('participant_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('tg_id', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(length=30), nullable=False))
    op.drop_constraint('users_Profile_ID_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_Participant_ID_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'profiles', ['profile_id'], ['id'])
    op.create_foreign_key(None, 'users', 'participants', ['participant_id'], ['id'])
    op.drop_column('users', 'Tg_id')
    op.drop_column('users', 'User_name')
    op.drop_column('users', 'Profile_ID')
    op.drop_column('users', 'Participant_ID')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Participant_ID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('Profile_ID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('User_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('Tg_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_Participant_ID_fkey', 'users', 'participants', ['Participant_ID'], ['id'])
    op.create_foreign_key('users_Profile_ID_fkey', 'users', 'profiles', ['Profile_ID'], ['id'])
    op.drop_column('users', 'username')
    op.drop_column('users', 'tg_id')
    op.drop_column('users', 'participant_id')
    op.drop_column('users', 'profile_id')
    op.add_column('profiles', sa.Column('Age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('profiles', sa.Column('Name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('profiles', sa.Column('About', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
    op.add_column('profiles', sa.Column('Sex', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('profiles', sa.Column('Date_birth', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('profiles', sa.Column('Photo', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.add_column('profiles', sa.Column('Religion', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.drop_column('profiles', 'about')
    op.drop_column('profiles', 'religion')
    op.drop_column('profiles', 'sex')
    op.drop_column('profiles', 'date_birth')
    op.drop_column('profiles', 'photo')
    op.drop_column('profiles', 'age')
    op.drop_column('profiles', 'name')
    # ### end Alembic commands ###
