"""redo 4

Revision ID: 86f863f80abe
Revises: e224f2cbfa26
Create Date: 2024-07-04 17:54:56.978366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86f863f80abe'
down_revision: Union[str, None] = 'e224f2cbfa26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('matches_profileid_2_fkey', 'matches', type_='foreignkey')
    op.drop_constraint('matches_profileid_1_fkey', 'matches', type_='foreignkey')
    op.create_foreign_key(None, 'matches', 'profiles', ['profileid_1'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'matches', 'profiles', ['profileid_2'], ['id'], ondelete='CASCADE')
    op.drop_constraint('metrics_profile_id_fkey', 'metrics', type_='foreignkey')
    op.create_foreign_key(None, 'metrics', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('participants_room_id_fkey', 'participants', type_='foreignkey')
    op.create_foreign_key(None, 'participants', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participants', type_='foreignkey')
    op.create_foreign_key('participants_room_id_fkey', 'participants', 'rooms', ['room_id'], ['id'])
    op.drop_constraint(None, 'metrics', type_='foreignkey')
    op.create_foreign_key('metrics_profile_id_fkey', 'metrics', 'profiles', ['profile_id'], ['id'])
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.create_foreign_key('matches_profileid_1_fkey', 'matches', 'profiles', ['profileid_1'], ['id'])
    op.create_foreign_key('matches_profileid_2_fkey', 'matches', 'profiles', ['profileid_2'], ['id'])
    # ### end Alembic commands ###
