"""Added matches

Revision ID: 25bd9365479a
Revises: b52980fbd349
Create Date: 2024-07-23 13:47:44.675659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25bd9365479a'
down_revision: Union[str, None] = 'b52980fbd349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('primary_id', sa.BigInteger(), nullable=True))
    op.add_column('matches', sa.Column('secondary_id', sa.BigInteger(), nullable=True))
    op.drop_constraint('matches_profileid_2_fkey', 'matches', type_='foreignkey')
    op.drop_constraint('matches_profileid_1_fkey', 'matches', type_='foreignkey')
    op.create_foreign_key(None, 'matches', 'profiles', ['secondary_id'], ['id'])
    op.create_foreign_key(None, 'matches', 'profiles', ['primary_id'], ['id'])
    op.drop_column('matches', 'id')
    op.drop_column('matches', 'profileid_2')
    op.drop_column('matches', 'profileid_1')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('profileid_1', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('matches', sa.Column('profileid_2', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('matches', sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.create_foreign_key('matches_profileid_1_fkey', 'matches', 'profiles', ['profileid_1'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('matches_profileid_2_fkey', 'matches', 'profiles', ['profileid_2'], ['id'], ondelete='CASCADE')
    op.drop_column('matches', 'secondary_id')
    op.drop_column('matches', 'primary_id')
    # ### end Alembic commands ###
