"""Database creation

Revision ID: 1c707ca44a76
Revises: 
Create Date: 2024-06-25 22:30:00.837109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c707ca44a76'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Age', sa.Integer(), nullable=False),
    sa.Column('Photo', sa.String(length=40), nullable=False),
    sa.Column('Date_birth', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('Sex', sa.Integer(), nullable=False),
    sa.Column('Religion', sa.String(length=40), nullable=False),
    sa.Column('About', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('Profile_ID', sa.Integer(), nullable=True),
    sa.Column('Participant_ID', sa.Integer(), nullable=True),
    sa.Column('Tg_id', sa.BigInteger(), nullable=True),
    sa.Column('User_name', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Participant_ID'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['Profile_ID'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('profiles')
    op.drop_table('participants')
    # ### end Alembic commands ###
