"""redo full db

Revision ID: b7396d04f801
Revises: 30c66226c001
Create Date: 2024-07-01 16:44:47.901314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7396d04f801'
down_revision: Union[str, None] = '30c66226c001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('occupacy', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('profileid_1', sa.Integer(), nullable=True),
    sa.Column('profileid_2', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profileid_1'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['profileid_2'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metrics',
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('participants', sa.Column('room_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'participants', 'rooms', ['room_id'], ['id'])
    op.alter_column('profiles', 'username',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('profiles', 'photo_url',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('users', 'tg_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'tg_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('profiles', 'photo_url',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('profiles', 'username',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_constraint(None, 'participants', type_='foreignkey')
    op.drop_column('participants', 'room_id')
    op.drop_table('metrics')
    op.drop_table('matches')
    op.drop_table('rooms')
    # ### end Alembic commands ###
