"""Change date of birth to str type

Revision ID: c9108ac1c75b
Revises: ae7c8370f2c5
Create Date: 2024-07-12 12:28:40.867099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9108ac1c75b'
down_revision: Union[str, None] = 'ae7c8370f2c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'date_of_birth',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'date_of_birth',
               existing_type=sa.String(length=10),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###
