"""Reset DB history

Revision ID: a15bbe989ec1
Revises: 
Create Date: 2024-07-09 15:31:36.158893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a15bbe989ec1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('occupacy', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('photo_url', sa.String(length=200), nullable=False),
    sa.Column('auth_date', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participants',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('room_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sex', sa.Integer(), nullable=True),
    sa.Column('religion', sa.String(length=40), nullable=True),
    sa.Column('about', sa.String(length=2000), nullable=True),
    sa.Column('hobby', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('soc_media', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('profileid_1', sa.BigInteger(), nullable=True),
    sa.Column('profileid_2', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['profileid_1'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profileid_2'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metrics',
    sa.Column('profile_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metrics')
    op.drop_table('matches')
    op.drop_table('profiles')
    op.drop_table('participants')
    op.drop_table('users')
    op.drop_table('rooms')
    # ### end Alembic commands ###
