"""Profile model redone and nullable values added where needed

Revision ID: 30c66226c001
Revises: 48608ac3258c
Create Date: 2024-06-27 12:04:30.844842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30c66226c001'
down_revision: Union[str, None] = '48608ac3258c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'sex',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('profiles', 'religion',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column('profiles', 'about',
               existing_type=sa.VARCHAR(length=2000),
               nullable=True)
    op.drop_column('profiles', 'tg_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('tg_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.alter_column('profiles', 'about',
               existing_type=sa.VARCHAR(length=2000),
               nullable=False)
    op.alter_column('profiles', 'religion',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('profiles', 'sex',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
