"""Logically separated user and profile

Revision ID: 4e1cbaf68142
Revises: 014d88a6fd52
Create Date: 2024-07-03 13:13:43.282429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e1cbaf68142'
down_revision: Union[str, None] = '014d88a6fd52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'last_name')
    op.drop_column('profiles', 'username')
    op.drop_column('profiles', 'first_name')
    op.drop_column('profiles', 'photo_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('photo_url', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('profiles', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('profiles', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('profiles', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
