"""Revised user and participant relations again

Revision ID: 48608ac3258c
Revises: ec75b9a2eec8
Create Date: 2024-06-26 16:18:55.888650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48608ac3258c'
down_revision: Union[str, None] = 'ec75b9a2eec8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tg_id')
    # ### end Alembic commands ###
