"""Added more logic to matches

Revision ID: 91bd2a35e1a7
Revises: 25bd9365479a
Create Date: 2024-07-23 14:22:17.351220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91bd2a35e1a7'
down_revision: Union[str, None] = '25bd9365479a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('primary_ack', sa.Boolean(), nullable=False))
    op.add_column('matches', sa.Column('secondary_ack', sa.Boolean(), nullable=False))
    op.alter_column('matches', 'primary_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('matches', 'secondary_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matches', 'secondary_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('matches', 'primary_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_column('matches', 'secondary_ack')
    op.drop_column('matches', 'primary_ack')
    # ### end Alembic commands ###
