"""redo the match db

Revision ID: fa8b5c7dc3d2
Revises: 2ac92b82bbda
Create Date: 2024-07-01 18:59:46.629779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa8b5c7dc3d2'
down_revision: Union[str, None] = '2ac92b82bbda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
