"""Added favorites, likes, and dislikes

Revision ID: b86990a3fc08
Revises: bb75ee21c3a4
Create Date: 2024-07-13 10:21:43.407352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b86990a3fc08'
down_revision: Union[str, None] = 'bb75ee21c3a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('likes', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('profiles', sa.Column('dislikes', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('profiles', sa.Column('favorites', postgresql.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'favorites')
    op.drop_column('profiles', 'dislikes')
    op.drop_column('profiles', 'likes')
    # ### end Alembic commands ###
